// src/features/game/world/locations/events/roomThemes.ts
export type GroundPattern = "slab" | "cracked" | "terrace" | "sand" | "grid" | "ash" | "ice" | "plate";
export type PropKind = "monolith" | "rig" | "reef" | "vault" | "pylon" | "ledger" | "cache" | "pyre" | "crystal" | "column";
export type ParticleKind = "dust" | "ember" | "bubble" | "spark" | "snow" | "rain" | "leaf";

export interface EventRoomTheme {
    id: string;
    locationId: string;
    name: string;
    radius: number;
    wallHeight: number;

    accent: number;
    trim: number;

    sky: number;
    fogDensity: number;

    ground: number;
    groundAccent: number;
    groundPattern: GroundPattern;

    wall: number;
    wallAccent: number;

    ambient: number;
    ambientIntensity: number;
    hemiSky: number;
    hemiGround: number;
    hemiIntensity: number;
    keyColor: number;
    keyIntensity: number;
    keyElevation: number;

    prop: PropKind;
    propCount: number;
    propColor: number;

    particle: ParticleKind;
    particleColor: number;
    particleCount: number;
}

export const EVENT_ROOM_THEMES: EventRoomTheme[] = [
    {
        id: "arena",
        locationId: "event-arena",
        name: "Candle Sanctum",
        radius: 60,
        wallHeight: 26,
        accent: 0x4ade80,
        trim: 0xeafff2,
        sky: 0x0e1014,
        fogDensity: 0.0062,
        ground: 0x2f2a24,
        groundAccent: 0x191612,
        groundPattern: "slab",
        wall: 0x3d332a,
        wallAccent: 0x584a3c,
        ambient: 0x38424e,
        ambientIntensity: 0.5,
        hemiSky: 0x6d7f9a,
        hemiGround: 0x1b1712,
        hemiIntensity: 0.55,
        keyColor: 0xbdd4ff,
        keyIntensity: 0.85,
        keyElevation: 62,
        prop: "column",
        propCount: 16,
        propColor: 0x4a4036,
        particle: "ember",
        particleColor: 0x9ef0bb,
        particleCount: 90,
    },
    {
        id: "dust2",
        locationId: "event-dust2",
        name: "Dust II",
        radius: 56,
        wallHeight: 30,
        accent: 0xff5757,
        trim: 0xffd2d2,
        sky: 0x180a0c,
        fogDensity: 0.0072,
        ground: 0x3a1c1e,
        groundAccent: 0x140809,
        groundPattern: "cracked",
        wall: 0x35191b,
        wallAccent: 0x5a2528,
        ambient: 0x4a1e22,
        ambientIntensity: 0.55,
        hemiSky: 0x8c3a3f,
        hemiGround: 0x140809,
        hemiIntensity: 0.5,
        keyColor: 0xff7a6a,
        keyIntensity: 1.15,
        keyElevation: 48,
        prop: "monolith",
        propCount: 14,
        propColor: 0x4d2124,
        particle: "dust",
        particleColor: 0xff9a8a,
        particleCount: 120,
    },
    {
        id: "pump",
        locationId: "event-pump",
        name: "The Ascent",
        radius: 58,
        wallHeight: 28,
        accent: 0xffd166,
        trim: 0xfff2cc,
        sky: 0x2a1a06,
        fogDensity: 0.0044,
        ground: 0x4a3413,
        groundAccent: 0x241806,
        groundPattern: "terrace",
        wall: 0x3d2c10,
        wallAccent: 0x7a5a1e,
        ambient: 0x6a4c14,
        ambientIntensity: 0.6,
        hemiSky: 0xffc766,
        hemiGround: 0x2a1c07,
        hemiIntensity: 0.7,
        keyColor: 0xffd98a,
        keyIntensity: 1.5,
        keyElevation: 34,
        prop: "rig",
        propCount: 18,
        propColor: 0x6d5019,
        particle: "spark",
        particleColor: 0xffe08a,
        particleCount: 130,
    },
    {
        id: "whale",
        locationId: "event-whale",
        name: "The Trench",
        radius: 62,
        wallHeight: 34,
        accent: 0x4fd1ff,
        trim: 0xd6f3ff,
        sky: 0x041824,
        fogDensity: 0.011,
        ground: 0x0e3346,
        groundAccent: 0x04161f,
        groundPattern: "sand",
        wall: 0x0a2735,
        wallAccent: 0x14536e,
        ambient: 0x0d3d55,
        ambientIntensity: 0.65,
        hemiSky: 0x3ba3cc,
        hemiGround: 0x03121a,
        hemiIntensity: 0.7,
        keyColor: 0x8fe4ff,
        keyIntensity: 0.9,
        keyElevation: 70,
        prop: "reef",
        propCount: 20,
        propColor: 0x15586e,
        particle: "bubble",
        particleColor: 0xa8ecff,
        particleCount: 150,
    },
    {
        id: "mint",
        locationId: "event-mint",
        name: "The Mint",
        radius: 54,
        wallHeight: 24,
        accent: 0xd4af50,
        trim: 0xffeab8,
        sky: 0x191307,
        fogDensity: 0.005,
        ground: 0x3a3020,
        groundAccent: 0x1b1610,
        groundPattern: "plate",
        wall: 0x2d2415,
        wallAccent: 0x6b5628,
        ambient: 0x574424,
        ambientIntensity: 0.55,
        hemiSky: 0xd6b060,
        hemiGround: 0x1b1610,
        hemiIntensity: 0.6,
        keyColor: 0xffdd9a,
        keyIntensity: 1.2,
        keyElevation: 52,
        prop: "vault",
        propCount: 16,
        propColor: 0x6f5a2c,
        particle: "spark",
        particleColor: 0xffe2a0,
        particleCount: 110,
    },
    {
        id: "bridge",
        locationId: "event-bridge",
        name: "The Span",
        radius: 58,
        wallHeight: 32,
        accent: 0xa855f7,
        trim: 0xe9d5ff,
        sky: 0x120720,
        fogDensity: 0.0058,
        ground: 0x2a1740,
        groundAccent: 0x110826,
        groundPattern: "grid",
        wall: 0x22123a,
        wallAccent: 0x4a2a76,
        ambient: 0x3d2166,
        ambientIntensity: 0.6,
        hemiSky: 0x9a63e0,
        hemiGround: 0x0d0620,
        hemiIntensity: 0.6,
        keyColor: 0xc79aff,
        keyIntensity: 1.05,
        keyElevation: 66,
        prop: "pylon",
        propCount: 12,
        propColor: 0x4d2c7a,
        particle: "spark",
        particleColor: 0xd6b0ff,
        particleCount: 140,
    },
    {
        id: "audit",
        locationId: "event-audit",
        name: "The Chamber",
        radius: 52,
        wallHeight: 26,
        accent: 0x8ad4ff,
        trim: 0xe2f5ff,
        sky: 0x1a2028,
        fogDensity: 0.0042,
        ground: 0x515a63,
        groundAccent: 0x2b3138,
        groundPattern: "slab",
        wall: 0x424a52,
        wallAccent: 0x6d7883,
        ambient: 0x9fb4c6,
        ambientIntensity: 0.7,
        hemiSky: 0xd2e6f5,
        hemiGround: 0x2b3138,
        hemiIntensity: 0.85,
        keyColor: 0xf2f8ff,
        keyIntensity: 1.55,
        keyElevation: 78,
        prop: "ledger",
        propCount: 18,
        propColor: 0x69737d,
        particle: "dust",
        particleColor: 0xdcecf7,
        particleCount: 100,
    },
    {
        id: "airdrop",
        locationId: "event-airdrop",
        name: "The Drop Zone",
        radius: 60,
        wallHeight: 22,
        accent: 0x7dffb0,
        trim: 0xdcffe9,
        sky: 0x0a1c16,
        fogDensity: 0.0056,
        ground: 0x1e3b2c,
        groundAccent: 0x0c1c15,
        groundPattern: "sand",
        wall: 0x183125,
        wallAccent: 0x2c5b43,
        ambient: 0x214c38,
        ambientIntensity: 0.6,
        hemiSky: 0x5fd898,
        hemiGround: 0x0a1a13,
        hemiIntensity: 0.7,
        keyColor: 0xb6ffd6,
        keyIntensity: 1.1,
        keyElevation: 58,
        prop: "cache",
        propCount: 22,
        propColor: 0x2e6047,
        particle: "rain",
        particleColor: 0xa6ffcd,
        particleCount: 220,
    },
    {
        id: "burn",
        locationId: "event-burn",
        name: "The Pyre",
        radius: 56,
        wallHeight: 28,
        accent: 0xff8a3c,
        trim: 0xffd9bd,
        sky: 0x1c0b04,
        fogDensity: 0.0078,
        ground: 0x3a1e10,
        groundAccent: 0x160903,
        groundPattern: "ash",
        wall: 0x2c1508,
        wallAccent: 0x6a3011,
        ambient: 0x5e2a0e,
        ambientIntensity: 0.6,
        hemiSky: 0xd8622a,
        hemiGround: 0x140702,
        hemiIntensity: 0.65,
        keyColor: 0xffa159,
        keyIntensity: 1.05,
        keyElevation: 44,
        prop: "pyre",
        propCount: 14,
        propColor: 0x5a2a12,
        particle: "ember",
        particleColor: 0xffb066,
        particleCount: 180,
    },
    {
        id: "diamond",
        locationId: "event-diamond",
        name: "The Vault of Hands",
        radius: 54,
        wallHeight: 30,
        accent: 0xb8f2ff,
        trim: 0xf2fdff,
        sky: 0x0a1a24,
        fogDensity: 0.0062,
        ground: 0x24404f,
        groundAccent: 0x101f28,
        groundPattern: "ice",
        wall: 0x1c3441,
        wallAccent: 0x3d6a80,
        ambient: 0x2c5a70,
        ambientIntensity: 0.65,
        hemiSky: 0x8fd8ee,
        hemiGround: 0x0d1c24,
        hemiIntensity: 0.75,
        keyColor: 0xdff6ff,
        keyIntensity: 1.35,
        keyElevation: 72,
        prop: "crystal",
        propCount: 20,
        propColor: 0x4e8ba3,
        particle: "snow",
        particleColor: 0xdff6ff,
        particleCount: 200,
    },
];

export const EVENT_ROOM_THEMES_BY_ID = new Map(EVENT_ROOM_THEMES.map((theme) => [theme.id, theme]));
export const EVENT_ROOM_THEMES_BY_LOCATION = new Map(EVENT_ROOM_THEMES.map((theme) => [theme.locationId, theme]));
